//
//  AuthorsListViewController.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorsListDisplayLogic: class {
    func displayAuthors(viewModel: AuthorsList.FetchAuthors.ViewModel)
    func displayError(viewModel: AuthorsList.Error.ViewModel)
}

class AuthorsListViewController: UIViewController, AuthorsListDisplayLogic {
    
    // MARK: Layout properties
    
    var contentView: AuthorsListContentViewProtocol?
    
    // MARK: Properties
    
    var interactor: AuthorsListBusinessLogic?
    private var router: AuthorsListRoutingLogic?
    private var imageWorker: ImageWorkLogic?

    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?){
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
  
    required init?(coder aDecoder: NSCoder){
        super.init(coder: aDecoder)
    }

    convenience init(interactor: AuthorsListBusinessLogic?,
                     router: AuthorsListRoutingLogic?,
                     imageWorker: ImageWorkLogic?) {
        self.init(nibName: nil, bundle: nil)
        self.interactor = interactor
        self.router = router
        self.imageWorker = imageWorker
        contentView = AuthorsListContentView(viewController: self, imageWorker: self.imageWorker)
        setupViewConfiguration()
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchFirstAuthors()
    }
  
    // MARK: Fetch data
  
    func fetchFirstAuthors() {
        interactor?.fetchFirstAuthors()
    }
    
    func fetchNextAuthors() {
        interactor?.fetchNextAuthors()
    }
  
    // MARK: AuthorsListDisplayLogic
    
    func displayAuthors(viewModel: AuthorsList.FetchAuthors.ViewModel) {
        contentView?.updateAuthors(displayedAuthors: viewModel.displayedAuthors)
    }

    func displayError(viewModel: AuthorsList.Error.ViewModel) {
        contentView?.updateAuthors(displayedAuthors: [])
        DispatchQueue.main.async {
            let alert = UIAlertController.standardMessage(title: viewModel.title,
                                                          message: viewModel.message,
                                                          completion: nil)
            self.present(alert, animated: true, completion: nil)
        }
    }
}

extension AuthorsListViewController: ViewCodingProtocol {
    func buildViewHierarchy() {
        guard let contentView = contentView else { return }
        view.addSubview(contentView)
    }
    
    func setupConstraints() {
        contentView?.constraint {[
            $0.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            $0.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor),
            $0.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
            $0.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
        ]}
    }
    
    func configureViews() {
        contentView?.backgroundColor = .blue
    }
}
