//
//  AuthorsListModels.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Services

enum AuthorsList {

    // MARK: Use cases
  
    enum FetchAuthors {
        struct Request {
        }
        struct Response {
            var authors: Authors
        }
        struct ViewModel {
            var displayedAuthors: [DisplayedAuthor]
        }
    }
    
    struct DisplayedAuthor {
        var id: Int
        var name: String
        var avatarUrl: String
    }
}
