//
//  AuthorsListWorker.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Services

protocol AuthorsListWorkLogic {
    func requestAuthors(completion: @escaping (Authors?, Error?) -> Void)
}

class AuthorsListWorker: AuthorsListWorkLogic {
    
    var service: BlogApi
    
    // MARK: Object Lifecycle
    
    init(service: BlogApi) {
        self.service = service
    }
    
    // MARK: AuthorsListWorkLogic
    
    func requestAuthors(completion: @escaping (Authors?, Error?) -> Void) {
        service.requestAuthors { authors, error in
            completion(authors, error)
        }
    }
}
