//
//  AuthorDetailsBuilder.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Services
import Ivorywhite

class AuthorDetailsBuilder {

    private var service: BlogApi
    
    init(service: BlogApi) {
        self.service = service
    }
    
    func build() -> AuthorDetailsViewController {
        let netServiceForImageDownloaging = Ivorywhite.shared.service(debugMode: false)
        let imageWorker = ImageWorker(service: netServiceForImageDownloaging)

        let presenter = AuthorDetailsPresenter()
        let worker = AuthorDetailsWorker(service: service)
        let interactor = AuthorDetailsInteractor(presenter: presenter, worker: worker)
        let router = AuthorDetailsRouter(dataStore: interactor)
        let viewController = AuthorDetailsViewController(interactor: interactor,
                                                       router: router,
                                                       imageWorker: imageWorker)
        router.viewController = viewController
        presenter.viewController = viewController

        return viewController
    }
}
