//
//  AuthorDetailsPresenter.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Services

protocol AuthorDetailsPresentationLogic {
    func presentAuthor(_ author: Author?)
    func presentPosts(_ posts: Posts)
    func presentError(response: AuthorDetails.Error.Response)
}

class AuthorDetailsPresenter: AuthorDetailsPresentationLogic {
    weak var viewController: AuthorDetailsDisplayLogic?
  
    // MARK: AuthorDetailsPresentationLogic

    func presentAuthor(_ author: Author?) {
        viewController?.displayAuthor(author: author)
    }

    func presentPosts(_ posts: Posts) {
        viewController?.displayPosts(posts)
    }

    func presentError(response: AuthorDetails.Error.Response) {
        let viewModel = AuthorDetails.Error.ViewModel(title: "Error",
                                                    message: response.message)
        viewController?.displayError(viewModel: viewModel)
    }
}
