//
//  AuthorDetailsWorker.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Services
import Ivorywhite

protocol AuthorDetailsWorkLogic {
    func requestPosts(authorId: Int,
                      page: Int,
                      postsPerPage: Int?,
                      orderBy: PostsOrderBy?,
                      direction: SortDirection?,
                      completion: @escaping (Posts?, Error?) -> Void)
}

class AuthorDetailsWorker: AuthorDetailsWorkLogic {
    
    var service: BlogApi
    
    // MARK: Object Lifecycle
    
    init(service: BlogApi) {
        self.service = service
    }
    
    // MARK: AuthorDetailsWorkLogic
    
    func requestPosts(authorId: Int,
                      page: Int,
                      postsPerPage: Int?,
                      orderBy: PostsOrderBy?,
                      direction: SortDirection?,
                      completion: @escaping (Posts?, Error?) -> Void) {
        service.requestPosts(authorId: authorId,
                             page: page,
                             postsPerPage: postsPerPage,
                             orderBy: orderBy,
                             direction: direction) { posts, error in
            if let _error = error {
                completion(posts, _error)
            } else {
                completion(posts, error)
            }
        }
    }
}
