//
//  AuthorDetailsModels.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Services

enum AuthorDetails {

    // MARK: Use cases
  
    enum FetchAuthors {
        struct Response {
            var author: Author
        }
        struct ViewModel {
            var displayedAuthor: Author
        }
    }

    enum Error {
        struct Response {
            var message: String
        }
        struct ViewModel {
            var title: String
            var message: String
        }
    }
}
