//
//  AuthorDetailsPresenter.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Services

protocol AuthorDetailsPresentationLogic {
    func presentAuthor(_ author: Author?)
    func presentPosts(_ posts: Posts)
    func presentError(_ error: Error)
}

class DisplayedPost {
    var post: Post
    var hasImage: Bool
    init(post: Post, hasImage: Bool) {
        self.post = post
        self.hasImage = hasImage
    }
}

class AuthorDetailsPresenter: AuthorDetailsPresentationLogic {
    weak var viewController: AuthorDetailsDisplayLogic?
  
    // MARK: AuthorDetailsPresentationLogic

    func presentAuthor(_ author: Author?) {
        viewController?.displayAuthor(author)
    }

    func presentPosts(_ posts: Posts) {
        let displayedPosts = posts.compactMap {
            return DisplayedPost(post: $0, hasImage: true)
        }
        viewController?.displayPosts(displayedPosts)
    }

    func presentError(_ error: Error) {
        viewController?.displayError(title: "Error", message: error.localizedDescription)
    }
}
