//
//  AuthorDetailsRouter.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorDetailsRoutingLogic {
    var dataStore: AuthorDetailsDataStore? { get }
    func routeToAuthorDetails()
}

protocol AuthorDetailsDataPassing {
    var dataStore: AuthorDetailsDataStore? { get }
}

class AuthorDetailsRouter: AuthorDetailsRoutingLogic, AuthorDetailsDataPassing {

    weak var viewController: AuthorDetailsViewController?
    var dataStore: AuthorDetailsDataStore?

    init(dataStore: AuthorDetailsDataStore?) {
        self.dataStore = dataStore
    }
 
    // MARK: Routing
    
    func routeToAuthorDetails() {
//        let storyboard = UIStoryboard(name: "Main", bundle: nil)
//        let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! AuthorDetailsViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation
    
//    func navigateToSomewhere(source: AuthorDetailsViewController, destination: AuthorDetailsViewController) {
//        source.show(destination, sender: nil)
//    }
  
    // MARK: Passing data
    
//    func passDataToSomewhere(source: AuthorDetailsDataStore, destination: inout AuthorDetailsDataStore) {
//        destination.name = source.name
//    }
}
