//
//  AuthorsListWorkerTests.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TheBlog
import XCTest

class AuthorsListWorkerTests: XCTestCase {
    
    // MARK: Subject under test
    var sut: AuthorsListWorker!
  
    // MARK: Tests
  
    func testRequestAuthors(){
        // Given
        let service = BlogServiceMock()
        sut = AuthorsListWorker(service: service)
        
        // When
        sut.requestAuthors(page: 1, authorsPerPage: 4) { authors, error in
            
            let author = authors!.first!
            
            // Then
            XCTAssertTrue(service.requestAuthorsCalled, "requestAuthors should call the service requestAuthors method")
            XCTAssertEqual(authors?.count, 4, "The Author object returned is not correct")
            XCTAssertEqual(author.id, 1, "The Author object returned is not correct")
        }
    }
}
