//
//  AuthorDetailsWorkerTests.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TheBlog
import XCTest

class AuthorDetailsWorkerTests: XCTestCase {
    
    // MARK: Subject under test
    var sut: AuthorDetailsWorker!
  
    // MARK: Tests
  
    func testRequestPosts(){
        // Given
        let service = BlogServiceMock()
        sut = AuthorDetailsWorker(service: service)
        
        // When
        sut.requestPosts(authorId: 1, page: 1, postsPerPage: 4, orderBy: .date, direction: .asc) { (posts, error) in
            let post = posts!.first!

            // Then
            XCTAssertTrue(service.requestPostsCalled, "requestPosts should call the service requestPosts method")
            XCTAssertEqual(posts?.count, 4, "The Posts object returned is not correct")
            XCTAssertEqual(post.id, 10, "The Post object returned is not correct")
        }
    }
}
