//
//  AuthorDetailsPresenterTests.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TheBlog
import XCTest
import Services

class AuthorDetailsPresenterTests: XCTestCase {
    // MARK: Subject under test
    var sut: AuthorDetailsPresenter!
  
  // MARK: Tests

    func testPresentAuthor() {
        // Given
        sut = AuthorDetailsPresenter()
        let spy = AuthorDetailsDisplayLogicSpy()
        sut.viewController = spy

        let dataMock = BlogServiceMock()

        // When
        sut.presentAuthor(dataMock.authorsMock.first!)

        // Then
        XCTAssertTrue(spy.displayAuthorCalled,
                      "presentPosts() should ask the view controller to display the result")
    }

    func testPresentPosts() {
        // Given
        sut = AuthorDetailsPresenter()
        let spy = AuthorDetailsDisplayLogicSpy()
        sut.viewController = spy

        // When
        sut.presentPosts([])
    
        // Then
        XCTAssertTrue(spy.displayPostsCalled,
                      "presentPosts() should ask the view controller to display the result")
    }

    func testPresentError() {
        // Given
        sut = AuthorDetailsPresenter()
        let spy = AuthorDetailsDisplayLogicSpy()
        sut.viewController = spy

        // When
        sut.presentError(NSError(domain: "Error", code: 0, userInfo: nil))

        // Then
        XCTAssertTrue(spy.displayErrorCalled, "presentError() should ask the view controller to display the error")
    }
}

// MARK: Test doubles

class AuthorDetailsDisplayLogicSpy: AuthorDetailsDisplayLogic {
    var displayAuthorCalled = false
    var displayPostsCalled = false
    var displayErrorCalled = false

    func displayAuthor(_ author: Author?) {
        displayAuthorCalled = true
    }

    func displayPosts(_ displayedPosts: Posts) {
        displayPostsCalled = true
    }

    func displayError(title: String, message: String) {
        displayErrorCalled = true
    }
}
