//
//  PostDetailsWorkerTests.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TheBlog
import XCTest

class PostDetailsWorkerTests: XCTestCase {
    
    // MARK: Subject under test
    var sut: PostDetailsWorker!
  
    // MARK: Tests
  
    func testRequestAuthors(){
        // Given
        let service = BlogServiceMock()
        sut = PostDetailsWorker(service: service)
        
        // When
        sut.requestComments(postId: 10, page: 1, commentsPerPage: 4, orderBy: .date, direction: .asc) { (comments, error) in

            let comment = comments!.first!

            // Then
            XCTAssertTrue(service.requestCommentsCalled,
                          "requestComments should call the service requestComments method")
            XCTAssertEqual(comments?.count, 4, "The comments object returned is not correct")
            XCTAssertEqual(comment.id, 100, "The Comment object returned is not correct")
        }
    }
}
