//
//  PostDetailsPresenter.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Services

protocol PostDetailsPresentationLogic {
    func presentPost(_ post: Post?)
    func presentComments(_ comments: Comments)
    func presentError(_ error: Error)
}

class PostDetailsPresenter: PostDetailsPresentationLogic {
    weak var viewController: PostDetailsDisplayLogic?
  
    // MARK: PostDetailsPresentationLogic

    func presentPost(_ post: Post?) {
        if let _post = post,
            let postDate = Date.date(from: _post.date, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'") {

            let displayedPost = Post(id: _post.id,
                                     date: Date.string(from: postDate, format: "dd MMM yyyy HH:mm"),
                                     title: _post.title,
                                     body: _post.body,
                                     imageURL: _post.imageURL,
                                     authorID: _post.authorID)
            viewController?.displayPost(displayedPost)
        } else {
            viewController?.displayError(title: "Ops!", message: "Sorry, an unexpected error occurred")
        }
    }

    func presentComments(_ comments: Comments) {
        viewController?.displayComments(comments)
    }

    func presentError(_ error: Error) {
        viewController?.displayError(title: "Error", message: error.localizedDescription)
    }
}
