//
//  PostDetailsViewController.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Services

protocol PostDetailsDisplayLogic: class {
    func displayPost(_ Post: Post?)
    func displayComments(_ comments: Comments)
    func displayError(title: String, message: String)
}

class PostDetailsViewController: UIViewController, PostDetailsDisplayLogic {
    
    // MARK: Layout properties
    
    var contentView: PostDetailsContentViewProtocol?
    
    // MARK: Properties
    
    var interactor: PostDetailsBusinessLogic?
    var router: PostDetailsRoutingLogic?
    private var imageWorker: ImageWorkLogic?

    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?){
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
  
    required init?(coder aDecoder: NSCoder){
        super.init(coder: aDecoder)
    }

    convenience init(interactor: PostDetailsBusinessLogic?,
                     router: PostDetailsRoutingLogic?,
                     imageWorker: ImageWorkLogic?) {
        self.init(nibName: nil, bundle: nil)
        self.interactor = interactor
        self.router = router
        self.imageWorker = imageWorker
        contentView = PostDetailsContentView(viewController: self, imageWorker: self.imageWorker)
        setupViewConfiguration()
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        title = "Comments"
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
        fetchPost()
        fetchFirstPosts()
    }
  
    // MARK: Fetch data

    func fetchPost() {
        interactor?.fetchPost()
    }

    func fetchFirstPosts() {
        interactor?.fetchFirstComments()
    }

    func fetchNextPosts() {
        interactor?.fetchNextComments()
    }

    // MARK: PostDetailsDisplayLogic

    func displayPost(_ post: Post?) {
        contentView?.updatePost(post)
    }

    func displayComments(_ comments: Comments) {
        contentView?.updateComments(displayedComments: comments)
    }

    func displayError(title: String, message: String) {
        contentView?.updateComments(displayedComments: [])
        DispatchQueue.main.async {
            let alert = UIAlertController.standardMessage(title: title,
                                                          message: message,
                                                          completion: nil)
            self.present(alert, animated: true, completion: nil)
        }
    }
}

extension PostDetailsViewController: ViewCodingProtocol {
    func buildViewHierarchy() {
        guard let contentView = contentView else { return }
        view.addSubview(contentView)
    }
    
    func setupConstraints() {
        contentView?.constraint {[
            $0.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            $0.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor),
            $0.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
            $0.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
        ]}
    }
}
