//
//  PostDetailsPresenter.swift
//  TheBlog
//
//  Created by Marcio Garcia on 07/06/20.
//  Copyright (c) 2020 Oxl Tech. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Services

protocol PostDetailsPresentationLogic {
    func presentPost(_ Post: Post?)
    func presentComments(_ comments: Comments)
    func presentError(_ error: Error)
}

class PostDetailsPresenter: PostDetailsPresentationLogic {
    weak var viewController: PostDetailsDisplayLogic?
  
    // MARK: PostDetailsPresentationLogic

    func presentPost(_ Post: Post?) {
        viewController?.displayPost(Post)
    }

    func presentComments(_ comments: Comments) {
        viewController?.displayComments(comments)
    }

    func presentError(_ error: Error) {
        viewController?.displayError(title: "Error", message: error.localizedDescription)
    }
}
